Repository newrelic/nri-flex, pull requests merged in 2020-05, with the labels that each got.

#171 Documentation for the windows file api
  docs/apis/file.md
Labels: enhancement

#168 add windows file integration test
  integration-test/cmd_windows_test.go
  integration-test/configs/windows-csv-test.yml
  integration-test/configs/windows-json-test.yml
  integration-test/file_integration_linux_test.go
  integration-test/file_integration_test.go
  integration-test/file_integration_windows_test.go
  integration-test/http_linux_test.go
  integration-test/http_windows_test.go
  integration-test/json_csv_integration_test.go
Labels: enhancement

#173 adding ssl cert check example for windows
  examples/flexConfigs/windows-ssl-certificate-expiration-lookup.json
  examples/flexConfigs/windows-ssl-certificate-expiration-script.ps1
  examples/flexConfigs/windows-ssl-certificate-expiration.yml
Labels: example

#175 Official support for store variable function
  CHANGELOG.md
  docs/basics/functions.md
  docs/experimental/functions.md
Labels: documentation

#148 add Kubernetes documentation
  CHANGELOG.md
  README.md
  docs/README.md
  docs/apis/README.md
  docs/apis/commands.md
  docs/apis/file.md
  docs/basic-tutorial.md
  docs/basics/configure.md
  docs/basics/functions.md
  docs/basics/k8s_configure.md
  docs/experimental/functions.md
  examples/nri-flex-k8s.yml
Labels: documentation
